# Generated by Django 5.2.1 on 2025-05-14 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='base.customer'),
        ),
    ]
