# Generated by Django 5.2.1 on 2025-05-14 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_customer_id_alter_sale_customer_fk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='customer_fk',
            new_name='customer_id',
        ),
    ]
