# Generated by Django 5.2.1 on 2025-05-14 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_customer_fk_sale_customer_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='customer_id',
            new_name='user_id',
        ),
    ]
